# -*- coding: utf-8 -*-
"""9data_vistualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P74M6m8P2Sh63FMh99t1uFcJfsQBN6_2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Titanic-Dataset.csv')

df.head()

sns.boxenplot(x='Sex',y='Age',data=df)

plt.figure(figsize=(8,10))
sns.boxplot(x='Sex',y='Age',hue='Survived',data=df)

