# -*- coding: utf-8 -*-
"""CentralTendency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDdAoixChCzBw9PpXa1wrTFncm9ue3pX

Descriptive Statistics - Measures of Central Tendency and variability Perform the following
operations on any open source dataset (e.g., data.csv)

1.Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a 
dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical)
variables. For example, if your categorical variable is age groups and quantitative variable is 
income, then provide summary statistics of income grouped by the age groups. Create a list that
contains anumeric value for each response to the categorical variable.

2.Write a Python program to display some basic statistical details like percentile, mean, standard
deviation etc. of the species of ‘Iris- setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of iris.csv
dataset.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

df=pd.read_csv('iris.csv')

df.head()

print("table label",df["Species"].unique())

#basic statistic details of the iris dataset
'Iris-setosa'
setosa = df['Species']=='Iris-setosa'
df[setosa].describe()

'Iris-versicolor'
versicolor = df['Species']=='Iris-versicolor'
df[versicolor].describe()

'Iris-virginica'
virginica=df['Species']=='Iris-virginica'
df[virginica].describe()

